# Generated by Django 3.2.6 on 2021-10-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_no',
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
